### ISSUE TITLE
There's no csv files within data folder.

### ISSUE THREAD

**Issue by liujs1016** [Curf/CNN-for-Infrared-Spectroscopy-Classification#1]
There's no csv files within data folder.
When I rename all the .txt files to .csv files, I got this error
![error](https://user-images.githubusercontent.com/68044258/148010932-68c47f8e-4ae9-447a-99c2-c0a8bf72dac8.JPG)
.

**Comment by Curf** [comment]
I edited a bit and created a single notebook for use.  Try cloning the repo again and use the notebook...

 https://github.com/Curf/CNN-for-Infrared-Spectroscopy/blob/8cadca0dcc93bc6ac18f665a4b88a527cade46a7/complete_notebook_example.ipynb

**Comment by liujs1016** [comment]
Thank you very much, what is your version of tensorflow and keras?

**Comment by Curf** [comment]
> Thank you very much, what is your version of tensorflow and keras?

keras=2.7.0=pyhd8ed1ab_0
tensorboard=2.7.0=pypi_0
tensorboard-data-server=0.6.1=pypi_0
tensorboard-plugin-wit=1.8.1=pypi_0
tensorflow=2.7.0=pypi_0
tensorflow-estimator=2.7.0=pypi_0
tensorflow-io-gcs-filesystem=0.23.1=pypi_0


I have also added a `requirements.txt` file you can use for dependencies.
